name: tests

on:
  pull_request:
    branches: [main, dev]

jobs:
  test-runner:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: vegadb-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - run: npm i && npm run test:ci
        env:
          POSTGRES_TEST_DB_URI: 'postgres://test:test@localhost:5432/vegadb-test'
